### ISSUE TITLE
Authentication Seems to fail but doesn't

### ISSUE THREAD

**Issue by Sergprotector** [gautammishra/lyft-rides-python-sdk#4]
I got Lyft API credentials & did a fresh pip install.  Trying the first example:

`response = client.get_ride_types(37.7833, -122.4167)`

I got the following error:

> lyft_rides.errors.LyftIllegalState: Invalid token_type or token.

Having rechecked my credentials, I went to request.py & commented out lines 149 - 151 to exclude this check & the code now works.  

I'm not sure what the issue was though.

**Comment by enriquegh** [comment]
seems to be stemmed from #2 
Once that gets merged you should be able to make a request.

**Comment by gautammishra** [comment]
The issue was with validating the headers. This has been resolved after @enriquegh suggestion of adding '+' and '/' to the list of possible characters in the access_token.
