### ISSUE TITLE
Release new version to pypi

### ISSUE THREAD

**Issue by drkp** [gautammishra/lyft-rides-python-sdk#6]
Please release a new version that contains the fix from #5 and update PyPI.

This will allow a working version to be used by other projects. For example, I wrote a plugin for Home Assistant that uses this module.

**Comment by enriquegh** [comment]
+1

**Comment by enriquegh** [comment]
@gautammishra

**Comment by gautammishra** [comment]
The update version has been release on PyPI with version 0.2.
